name: '✨ 기능 추가'
description: '프로젝트에 새로운 기능을 추가합니다.'
title: '[Feat] '
labels:
  - 'enhancement'

body:
  - type: markdown
    attributes:
      value: |
        ### 기능 설명

  - type: textarea
    id: feature_description
    attributes:
      label: 기능 설명
      description: 추가할 기능에 대한 설명을 입력하세요.
      placeholder: 예) 이 기능은 사용자가 이메일과 비밀번호를 통해 로그인할 수 있도록 합니다.
    validations:
      required: true

  - type: textarea
    id: feature_necessity
    attributes:
      label: 필요성
      description: 이 기능이 왜 필요한지 설명하세요.
      placeholder: 예) 사용자 인증을 위해 필요합니다.
    validations:
      required: true

  - type: textarea
    id: feature_details
    attributes:
      label: 구현 세부 사항
      description: 기능 구현에 필요한 세부 사항을 설명하세요.
      placeholder: |
        예시
        1. 사용자가 이메일과 비밀번호를 입력하면 서버에서 인증을 처리합니다.
        2. 인증이 성공하면 사용자를 대시보드 페이지로 리디렉션합니다.

  - type: textarea
    id: reference_material
    attributes:
      label: 참고 자료
      description: 관련 문서나 레퍼런스 링크를 추가해주세요.
      placeholder: 예) https://developer.mozilla.org/ko/docs/Web/HTTP/Authentication

  - type: textarea
    id: additional_info
    attributes:
      label: 추가 정보
      description: 추가로 필요한 정보가 있다면 적어주세요.
      placeholder: 기타 필요한 정보가 있다면 여기에 추가하세요.
