name: '🐛 버그 수정'
description: '프로젝트 실행 중 발생한 버그를 수정합니다.'
title: '[Fix] '
labels:
  - 'bug'

body:
  - type: markdown
    attributes:
      value: |
        ### 버그 설명

  - type: input
    id: bug_summary
    attributes:
      label: 버그 요약
      description: 버그에 대한 간략한 설명을 입력하세요.
      placeholder: 예) 로그인 시도 시 에러 메시지가 표시되지 않음
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: 재현 방법
      description: 버그를 재현하는 방법을 단계별로 설명하세요.
      placeholder: |
        예시
        1. 로그인 페이지로 이동
        2. 잘못된 자격 증명 입력
        3. '로그인' 버튼 클릭
        4. 오류 메시지 미표시
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: 기대 동작
      description: 기대하는 동작을 설명하세요.
      placeholder: 예) 잘못된 자격 증명을 입력하면 적절한 오류 메시지가 표시되어야 합니다.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 스크린샷
      description: 오류를 보여주는 스크린샷을 추가해주세요.
      placeholder: 스크린샷을 여기에 추가하세요.

  - type: textarea
    id: additional_info
    attributes:
      label: 추가 정보
      description: 추가로 필요한 정보가 있다면 적어주세요.
      placeholder: 기타 필요한 정보가 있다면 여기에 추가하세요.
